acro5piano/react-native-big-calendar

README.md, src/Calendar.tsx, src/CalendarHeader.tsx
Good day!
In this PR, I am adding **onPressDateHeader** prop to Calendar, for callback when pressing Dates in the Header.
All the small changes are caused by Prettier so you can just ignore it.
Hope to hear from you soon as this feature is badly needed for my project. 
Thank you very much!
=> Add onPressDateHeader

src/CalendarHeader.tsx, stories/index.stories.tsx, tsconfig.json
close #85 
Ideally we have to find this kind of bugs by the power of TypeScript, so I've removed `dom` from `lib` in tsconfig.
=> Remove `event` dependency, fix tsconfig to ensure to work with React Native, close #85

src/Calendar.tsx, src/utils.ts
Day mode view has been implemented
=> Day mode implemented

src/Calendar.tsx, src/CalendarBody.tsx, src/CalendarEvent.tsx, src/CalendarHeader.tsx
- Fix type of event callback function
- Extract function from `React.memo` to show proper display name
=> fix type of event callback function, close #336

src/CalendarBody.tsx
Double checking that object exists before calling scrollTo method upon it
=> fixed scrollTo issue

README.md, src/CalendarBody.tsx, src/CalendarEvent.tsx, src/__tests__/utils.test.ts, src/interfaces.ts, src/utils.ts, stories/desktop.stories.tsx, stories/events.tsx
This fixes the typings on recent improvement https://github.com/acro5piano/react-native-big-calendar/pull/359
=> Feat custom event renderer // Fix types

src/CalendarBody.tsx
do not setInterval if hideNowIndicator
=> do not setInterval if hideNowIndicator

README.md, src/Calendar.tsx, src/CalendarBody.tsx, src/CalendarEvent.tsx, src/DefaultCalendarEventRenderer.tsx, src/index.ts, src/interfaces.ts, stories/desktop.stories.tsx, stories/events.tsx, tsconfig.json
breaking: remove `renderEvent` and add custom render function capability
=> breaking: remove `eventRenderer` and add custom render function capability

src/components/CalendarBody.tsx, stories/desktop.stories.tsx
fix Events spanning multiple days not rendering correct
=> fix Events spanning multiple days not rendering correct, close #385

README.md
=> fix docs [skip ci]

.babelrc, package.json, src/commonStyles.ts, src/components/Calendar.tsx, src/components/CalendarBody.tsx, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarEventForMonthView.tsx, src/components/CalendarHeaderForMonthView.tsx, src/interfaces.ts, stories/desktop.stories.tsx, stories/events.tsx, stories/mobile.stories.tsx, yarn.lock
fix month view for mobile, fix #444
=> fix month view for mobile, fix #444

package.json, rndemo/App.tsx, rndemo/index.js, src/commonStyles.ts, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarEventForMonthView.tsx, src/components/CalendarHeaderForMonthView.tsx
- [hotfix] Fix css properties on platform native #470
- Add `key` prop for month view components
- Fix Demo app usability
=> [hotfix] Fix css properties on platform native

rndemo/App.tsx, rndemo/android/app/src/main/res/values/styles.xml, rndemo/index.js, rndemo/package.json, rndemo/yarn.lock, src/commonStyles.ts, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarEvent.tsx, yarn.lock
update deps, fix Android start/end property, fix Android css
=> update deps, fix Android start/end property, fix Android css

package.json, src/__tests__/utils.test.ts, src/components/CalendarContainer.tsx, src/components/CalendarHeader.tsx, src/index.ts, stories/desktop.stories.tsx, yarn.lock
add all day example to calendar, fix all day style
=> add all day example to calendar, fix all day style

README.md, rndemo/App.tsx, src/__tests__/utils.test.ts, src/components/Calendar.tsx, src/components/CalendarBody.tsx, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx, src/components/CalendarEvent.tsx, src/components/CalendarEventForMonthView.tsx, src/components/CalendarHeader.tsx, src/components/DefaultCalendarEventRenderer.tsx, src/hooks/useCalendarTouchableOpacityProps.ts, src/interfaces.ts, src/utils.ts, stories/desktop.stories.tsx, stories/events.tsx, stories/hooks.ts, stories/issue-575.stories.tsx, tsconfig.json
show All day events on the month view, set onPressEvent handler to all day events ( close #575 )
=> show All day events on the month view, set onPressEvent handler to all day events ( close #575 )

src/components/CalendarContainer.tsx, stories/full-customization.stories.tsx
resolve infinte rendering issue on onChange Date
Related: https://github.com/acro5piano/react-native-big-calendar/issues/712
=> fix infinite setState onChangeDate

src/components/CalendarContainer.tsx, src/interfaces.ts, stories/issue-712.stories.tsx, stories/mobile.stories.tsx
This pr Fixes these issues:
- Issues with onChangeDate (infinite setState) #712
- Swipe RTL is working fine, but Swipe LTR always goes to previous month last date #795
@aleksays was trying to fix the issue on #797, but this issue can be resolved by reverting the previous change created on #764 and make implement a proper fix.
=> fix infinite setState, fix onChangeDate (closes #795)

src/components/Calendar.tsx
require merge-anything workaround
=> require merge-anything workaround

src/components/CalendarContainer.tsx, src/interfaces.ts, stories/desktop.stories.tsx
enable to pass array of style (in type level)
=> enable to pass array of style (in type level)

rndemo/App.tsx, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx
Added new attribute OnPressMoreLabel which has two arguments Events, Date.
=> Feature : Clickable More Label

src/components/CalendarContainer.tsx, src/utils/datetime.ts, stories/issue-961.stories.tsx
fix #961, fix duplicated onChangeDate calls
=> fix #961, fix duplicated onChangeDate calls

src/hooks/usePanResponder.ts
refactor: use ref for value which should not triger re-render
=> refactor: use ref for value which should not triger re-render

src/components/Calendar.tsx
fix: prevent the default theme being changed
=> fix: prevent the default theme being changed

src/components/CalendarContainer.tsx, src/components/Schedule.tsx
Hi @acro5piano 
I had the same problem as issue #1038, so I fixed it. Please consider this PR.
Thank you!
- Before
- After
=> fix: locale not working in schedule mode

README.md, src/components/CalendarBody.tsx, src/components/CalendarContainer.tsx, src/components/HourGuideColumn.tsx, src/interfaces.ts, stories/desktop.stories.tsx, stories/events.tsx
This feature add props to customize hour component
=> feat(hour): add feature to render custom component for hour

src/components/CalendarBodyForMonthView.tsx
Hi,
I was facing slowness when showing calendar in month view with a large sets of events. 
Using profiling tools, it shows that the calendar body will re-render after it sets calendarWidth/calendarCellHeight from layout events.
The changes i made is to prevent expensive logic to being run when calendarWidth has yet to be set. This make the first render of calendarBodyForMonthView a lot more efficient especially with a large sets of events.
Also make sure not to set calendarCellHeight when disableMonthEventCellPress is false, since it will cause calendarBodyForMonthView to re-render as well. 
For profiling i use react-devtools which captures the rendering of the components and why it was rendered:
=> optimize rendering performance for monthview for first render

.github/workflows/release-beta.yml
=> ci: add beta release workflow

.github/workflows/release-beta.yml, .github/workflows/release.yml, bun.lock
=> fix: update deps, publish workflow

stories/issue-712.stories.tsx, stories/mobile.stories.tsx
Just adds a couple of type annotations because without them pre-commit `bun tsc` is failing
=> Add some missing type annotations in stories
