src/CalendarHeader.tsx
This is from the latest version 0.3.1. 
It works fine in Storybook and in a react-native project this is what it looks like.
This is caused by an extra `View` under the `TouchableOpacity` in `CalendarHeader.tsx`.
=> Fix to overlapped header in version 0.3.1.

src/__tests__/utils.test.ts, src/utils.ts
Missing `day` support in function `modeToNum`. Will cause error swipe in day mode.
Added simple test case for function `modeToNum` also.
=> Fix modeToNum in utils

src/CalendarBody.tsx, stories/events.tsx
In the current version 0.7.0, events that occur exactly at midnight do not get added to the calendar.  I used the isBetween dayjs plugin to compare event dates to the calendar dates to ensure they get added properly.
I don't think this needs any update to the readme because it is just a bugfix, but let me know if you need any more information. Thanks!
=> Fixes an issue with displaying events that occur at midnight

src/CalendarBody.tsx
Fix Scrolling issue on Android, close #335.
The prop `nestedScrollEnabled` was added since RN 0.64.0, so this library should follow the change.
https://github.com/facebook/react-native/commit/263d04d756321b3250d9ae700101f52d9663a2f0
https://github.com/facebook/react-native/pull/18299
https://github.com/facebook/react-native-website/pull/249
=> Fix Scrolling issue on Android, close #335

README.md, src/CalendarEvent.tsx, src/interfaces.ts, stories/desktop.stories.tsx, stories/events.tsx
This pull request adds the opportunity for a custom event renderer function.
Example use : 
```typescript
const eventRenderer = (event: DayJSConvertedEvent, touchableOpacityProps: any) => {
return (
<TouchableOpacity
{...touchableOpacityProps}
style={[
...touchableOpacityProps.style,
{
backgroundColor: 'white',
borderWidth: 1,
borderColor: 'lightgrey',
borderLeftColor: event.color
? event.color
: touchableOpacityProps.style[2].backgroundColor,
borderLeftWidth: 10,
borderStyle: 'solid',
borderRadius: 6,
alignItems: 'center',
justifyContent: 'center',
},
]}
>
{event.end.diff(event.start, 'minute') < 32 && showTime ? (
<Text style={{ ...commonStyles.eventTitle, color: 'black' }}>
{event.title},<Text style={styles.eventTime}>{event.start.format('HH:mm')}</Text>
</Text>
) : (
<>
<Text style={{ …
```
=> WIP: Add custom renderer for events

src/utils.ts
Fixes the issue where the change from day to week view would display the wrong week when the startOfWeek is not the default, closes #423
=> Fixes the issue described in #423

src/index.ts
1) For one of use case we have to just use CalendarBody component. But it was not accessible as we haven't exported it. Made changes related to it. We can now just render CalendarBody component.
2) Tested locally.
Thank you
=> Exported CalendarBody component

src/__tests__/utils.test.ts, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarEventForMonthView.tsx, src/index.ts, src/utils.ts, stories/desktop.stories.tsx, stories/events.tsx
Here's my take on implementing spanning events, for now I've only implemented it for the month mode.
In `CalendarBodyForMonthView` I've change the filtering and add sorting for better rendering, sorting could be handled on the client side but I think at least the one I've implemented is needed.
In `CalendarEventForMonthView` I determine how much of the event to show during the current week, then on the starting day of the event or the first day of the week (when the event spans over multiple weeks) I render the event with `position: absolute` and on the other days I render an empty `View` so that other events are push downed in the column.
I still think it needs more testing and review but It's a good start, main problem right now is render in landscape mode.
Please let me know your …
=> Support event spanning on month mode

README.md, src/components/CalendarContainer.tsx, src/components/CalendarHeader.tsx, src/utils.ts
At first, thank you for great library.
I want new feature to display date of blue style except today, so I added active date props to header on this PR.
=> add active date props to header

package.json
Support React Native 0.59 and newer versions - see issue #568 of acro5piano/react-native-big-calendar
=> Update package.json for issue 568

README.md, src/components/CalendarBody.tsx, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx, src/components/HourGuideCell.tsx, src/components/HourGuideColumn.tsx, src/interfaces.ts, src/theme/ThemeInterface.ts, src/theme/defaultTheme.ts, src/utils.ts, stories/desktop.stories.tsx, stories/mobile.stories.tsx, stories/themes.ts
Hi **@acro5piano**
As per discussion, I did changes to ad the support to provide styles to calendar cells based on the date of the cell. For this, I have to remove evenCellBg and oddCellBg.
I introduces 2 new props `calendarCellStyle` and `calendarCellTextStyle`.
```
`calendarCellStyle`: Use this prop to provide custom styles to calendar cells based on date of cell.
calendarCellStyle = ViewStyle | (date: dayjs.Dayjs, hourRowIndex?: Number | undefined) => ViewStyle)
```
```
`calendarCellTextStyle` : Use this prop to provide custom styles to calendar cells text for Month mode. It is needed if have text color of cell visible based on date
calendarCellTextStyle = ViewStyle | (date: dayjs.Dayjs, hourRowIndex?: Number | undefined) => ViewStyle)
```
Note: `hourRowIndex` can be used to give …
=> feat: add support to style calendar cells based on cell date

src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx
Added a way to have a callback for pressing the date in the cell of a month view.
I used `onPressDateHeader` in order to not have to add a new prop since it's the same usage, if you want a new one I will change it.
Falls back to `onPressCell` when not provided.
=> add onPressDateHeader for month view

src/__tests__/utils.test.ts, src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx, src/components/CalendarEventForMonthView.tsx, src/utils.ts, stories/desktop.stories.tsx, stories/events.tsx
Added a prop to show adjacent months dates.
I used `dayjs.date()` property `If the range is exceeded, it will bubble up to the months.` to repopulate `weeks` replacing `calendarize`'s zeros to extend the range.
I also fixed event spanning to fit the property.
Let me know what you think!
=> Show adjacent months dates on month view

src/components/CalendarBodyForMonthView.tsx, src/components/CalendarContainer.tsx
I found out that swipe back to February had a bug and would jump to January and looking into it I actually found in `full-customization.stories.tsx` that the code to move to the previous date on month mode was different so I fixed it using this.
=> Fix month view swipe back

src/components/CalendarBody.tsx, src/components/CalendarContainer.tsx
--added prop to Calendar component to make event Ordering in week/day view an optional feature
--this will improve the plugin performance considerably(10+ events) if one doesn't want this feature or wish to handle it separately in their own wrapper component.
Regarding #820
=> Optional Event ordering prop feature to improve performance of week/day view

src/components/CalendarBodyForMonthView.tsx
In this [PR](https://github.com/acro5piano/react-native-big-calendar/pull/892) , it seems that the behavior of `sortedMonthView` is accidently changed.
Before that PR, sorting logic is executed when sortedMonthView is true, but after it, sorting logic is run when sortedMonthView is false.
I thought that this could be misleading. So I fixed it.
[Before](https://github.com/acro5piano/react-native-big-calendar/pull/892/files#diff-09273721dcf5e4cfcef5b2c49d609294814ff7e89e5bada20461ad8907f2f54aL108-L109) and [After](https://github.com/acro5piano/react-native-big-calendar/pull/892/files#diff-09273721dcf5e4cfcef5b2c49d609294814ff7e89e5bada20461ad8907f2f54aR95-R98).
They are reversed.
=> Fixed accidently changed API behavior

src/utils/__tests__/datetime.test.ts, src/utils/datetime.ts
Lib crashes when sending an empty events array using the new enrichedEvents function.
- Added a clause to return empty when receiving an empty array
- Added unit test
=> fix: lib crashes when receiving empty events

src/components/CalendarBody.tsx, src/components/CalendarBodyForMonthView.tsx, src/components/Schedule.tsx, src/utils/__tests__/datetime.test.ts, src/utils/datetime.ts, stories/events.tsx, stories/mobile.stories.tsx
Recently I discovered we are having some issues on week mode when passing a larger dataset of events. This issue is caused due [HERE](https://github.com/acro5piano/react-native-big-calendar/blob/main/src/components/CalendarBody.tsx#L226-L264) we are filtering 3 times the event list in each re-render.
Now when enabling the enrichedEvents through the prop `enableEnrichedEvents` the lib will be using a new way to organize and render the events:
1. Lib preprocess the events creating a dictionary where the key is the date of the event and the value is the event itself.
a.  In case of multi-day events, the event will be duplicated (will be in all the keys from the start to the end date)
2. Lib renders the events inside a useCallback improving the performance on re-renders
3. we iterate just one …
=> feat: create custom renderer to improve performance on bigger datasets

src/components/CalendarBody.tsx, src/components/CalendarContainer.tsx
We've implemented a mechanism to leverage an internally optimized algorithm along with a dictionary for more efficient event rendering. Nevertheless, there are instances when the host app prefers to construct this dictionary independently, such as when handling it within a background job.
The library now exposes a prop to accept the enrichedEvents dictionary. When enableEnrichedEvents is activated, the library attempts to utilize this new property. If the dictionary is not provided, it gracefully falls back to constructing it internally.
=> feat: expose prop to be able to send the enriched dictionary

src/components/CalendarHeader.tsx
First of all, I would like to thank you for providing this component. We use it in our open source project, which is an app for our students.
I have added the locale property to the CalendarHeaderProps interface. In the _CalendarContainer component [(currently on line 377)](https://github.com/acro5piano/react-native-big-calendar/blob/main/src/components/CalendarContainer.tsx#L377) the locale value is stored in the headerProps constant. The headerProps constant is later transferred to the HeaderComponent component as properties. If a custom header renderer is programmed, the calendar transfers the desired language. In my humble opinion, this is good software design.
Unfortunately, you first have to read the code to recognize this fact, because the locale property is missing in the …
=> Add locale property to CalendarHeaderProps interface

src/components/CalendarBodyForMonthView.tsx
This is my first PR to this project.
I tried to fix the issue where events are hidden by the background color.
| before | after |
| ------------- | ------------- |
| When a background color is added by cell styling, the second and subsequent days of multi-day events are hidden. | I added a view that only applies background color behind the calendar cells and removed the background color styling from the cells. |
| ![image](https://github.com/user-attachments/assets/f1427b34-d139-4460-92b7-b084ca2e738b) | ![image](https://github.com/user-attachments/assets/1e378d8b-cab5-4a3a-9a62-ea5846af4fce) |
=> Fix: Multi-day events hidden by background color

src/components/CalendarBody.tsx, src/index.ts, src/utils/__tests__/datetime.test.ts, src/utils/datetime.ts
I used rndemo project in order to understand why modes of `week` `day` and `3days` where very slow when trying to navigate them.
To be able to render 87 events on `week` mode it was taking approx 1260ms
I applied to stress it even further with 500 events which took a bit over a minute 62seconds.
Of course this makes the library almost unusable since in all real life scenarios we will navigate from a screen to this one and that could take some time to render.
After i applied the proposed fixes
- 87 events loaded in just 88 milliseconds
- 500 events loaded in just 430 milliseconds
=> fix: improved performance speed for getOrderOfEvent and getCountOfEventsAtEvent methods

src/components/CalendarEventForMonthView.tsx
Hi,
with the existing margin top implementation for month view events, there are no gaps between multiday event and it doesn't look that nice.
By moving margin-top implementation to parent view instead of touchableopacity for the event, it looks neater.
=> better margin top implementation for multiday event in month view

src/components/CalendarBody.tsx, src/components/Schedule.tsx
**Fixed Event Grouping and Sorting in Schedule View**
**Event Sorting and Grouping Logic Update**:  
The logic for sorting and grouping events in the schedule view has been updated to ensure events are displayed in chronological order and properly grouped by date.  
- **Sorting**: Events are now sorted by their start date before being grouped, ensuring they appear in the correct sequence.
- **Grouping**: Events are grouped by their formatted start date, and the groups are now correctly ordered within the same month.
**New Month Transition Logic**:  
The logic for detecting the start of a new month has been updated to correctly reference the grouped events, ensuring the transition between months is accurate.
**Issue Discovery**:  
I noticed this bug after updating to the latest version …
=> **fix(schedule-month-separator): correct event grouping and sorting**

bun.lock, package.json
Since we have a clear README to install them along with our libraries, remove them from the dependency list and declare as peer dependencies.
=> fix: declare native libraries as peer dependencies

src/components/CalendarBodyForMonthView.tsx, stories/events.tsx
I tried to the issue where spanning events hide other events.
| before | after |
| ------------- | ------------- |
| Event6 is not visible because it is covered by Event2. | Event6 is visible. |
| ![image](https://github.com/user-attachments/assets/90beee85-202e-4862-a7d0-fd5e85a145f7) | ![image](https://github.com/user-attachments/assets/da4d6813-6b5d-436e-9d31-df60c50b7b34) |
=> Fix issue where spanning events hide other events

src/components/CalendarBody.tsx
Fixes an issue https://github.com/acro5piano/react-native-big-calendar/issues/1178 where scrolling of CalendarBody would not work inside InfinitePager on Android
Credit for fix is to @berkozturk97 as per his comment on the issue
Related issue from the pager library:
https://github.com/computerjazz/react-native-infinite-pager/issues/18
=> Use react-native-gesture-handler ScrollView in CalendarBody

src/components/CalendarBodyForMonthView.tsx, stories/desktop.stories.tsx, stories/events.tsx
Sorry, the fix I made in PR #1181 still contained the issues in cases with complex combinations of spanning events.
- Some events were hidden
- Some events were displayed multiple times
- Some events were not moved up even though there was space available
This PR resolves the above issues.
- `event4-1` and `event5-1` are not visible because they are covered by `event2`.
- `event6-3` is displayed three times.
- There is space available in the first row of Friday and Saturday.
- `event4-1` and `event5-1` are now visible.
- `event6-3` is displayed only once.
- Events are correctly moved up when space is available.
| before | after |
| ------------- | ------------- |
| <img width="400" alt="image" src="https://github.com/user-attachments/assets/68148436-aa85-4b09-94b3-7d9c683c8220" /> | <img …
=> Fix event move up behavior

src/hooks/usePanResponder.ts
I wrapped the Calendar component with ScrollView to enable vertical scrolling for large monthly calendars.
On iOS, I encountered an issue where vertical scrolling did not work correctly.
This PR resolves that issue.
In the `onMoveShouldSetPanResponder` of `PanResponder.create`, when the absolute value of `dy` was greater than 2, it returned `true`. This caused the function to return `true` in most cases when swiping vertically, interfering with the vertical scroll operations of the wrapping ScrollView.
To resolve this problem, I modified the logic to return `true` only when the absolute value of `dx / dy` is greater than 1 (when the horizontal movement of the swipe is greater than the vertical movement).
Additionally, this calculation is now only applied when `onSwipeHorizontal` exists.
=> Fix: resolve scroll conflicts with parent ScrollView
